### ISSUE TITLE
Meta in response

### ISSUE THREAD

**Issue by icebob** [ice-services/moleculer#176]
Send back the Context meta to the caller. (E.g. send back response headers to API gateway)

**Example to export & download a file:**
```js
// Export data
export(ctx) {
    const rows = this.adapter.find({});

    // Set headers to download as a file
    ctx.meta.headers = {
        "Content-Type": "application/json; charset=utf-8",
        "Content-Disposition": 'attachment; filename=\"book.json\"'
    }

    return rows;
}
```

**Authenticate:**
```js
auth(ctx) {
    let user = this.getUserByJWT(ctx.params.token);
    if (user) {
        ctx.meta.user = user;
        ctx.meta.session = uuid.v4(); // Generate a session ID

        return true;
    }

    throw new Forbidden();
}
```

## Tasks:
- [x] extend `RESPONSE` packet with `meta` field. It is an object (or JSON string) as in `REQUEST` packet
- [x] add new field to handle by transporter (`_responseHandler`, `sendResponse`)
- [x] update schema-based serializers (ProtoBuf, Avro)
- [x] add relevant tests.
- [x] increase protocol version
- [x] update PROTOCOL.md
