### ISSUE TITLE
moleculer CLI tool

### ISSUE THREAD

**Issue by icebob** [ice-services/moleculer#18]
Create a CLI tool to generate moleculer base project & services from templates.

**Tasks**
- [x] `moleculer init` - generate an empty moleculer base project from a template
- [x] `moleculer add service` - create a new service file. Prompted values: name, version, action names. Create service file and put to the `services` folder.
- [x] `moleculer connect <connectionstring>` - connect to a transporter or start a local broker. After it switch to REPL mode with [vorpal](https://github.com/dthree/vorpal). Available commands: `call`, `event`, `loadService`

**Comment by icebob** [comment]
In progress: https://github.com/ice-services/moleculer-cli
